name: Feature Request
description: Request a new feature
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature!
  - type: textarea
    id: feature-description
    attributes:
      label: New feature
      description: Description of the new feature
      value: "New automatic method should do thing"
    validations:
      required: true
  - type: textarea
    id: feature-reason
    attributes:
      label: Why this new feature
      description: Describe why this new feature should be added to Georm
      value: "I use that workaround very often, this new method will simplify it"
    validations:
      required: true
  - type: textarea
    id: ideas-implementation
    attributes:
      label: Implementation ideas and additional thoughts
      description: Do you have an idea on how to implement it?
      value: "It could be implemented doing foo, bar, and baz"
    validations:
      required: false
