services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: georm-backend-db
    environment:
      POSTGRES_PASSWORD: georm
      POSTGRES_USER: georm
      POSTGRES_DB: georm
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - georm_backend_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    restart: unless-stopped
    container_name: georm-backend-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: true
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - georm_backend_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  georm_backend_db_data:
  georm_backend_pgadmin_data:
